// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-budget-summary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function activeProfile(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("financial_profiles").select("id, name, type, is_active").order("is_active", { ascending: false }).limit(1);
  if (error) throw new Error(error.message);
  const profile = data?.[0];
  if (!profile) throw new Error("No financial profile found for this account.");
  return { supabase, profile };
}

// src/lib/mcp/tools/get-budget-summary.ts
var get_budget_summary_default = defineTool({
  name: "get_budget_summary",
  title: "Get budget summary",
  description: "Summarize the signed-in user's active budget profile: total monthly income, debt minimum payments, fixed and variable expenses, savings balances and the resulting monthly cashflow.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { supabase, profile } = await activeProfile(ctx);
    const now = /* @__PURE__ */ new Date();
    const month = now.getMonth() + 1;
    const [income, debts, fixed, variable, savings, goals] = await Promise.all([
      supabase.from("income_sources").select("amount, income_type").eq("profile_id", profile.id),
      supabase.from("debts").select("balance, minimum_payment").eq("profile_id", profile.id),
      supabase.from("fixed_expenses").select("amount, frequency_type, payment_month").eq("profile_id", profile.id),
      supabase.from("variable_expenses").select("amount").eq("profile_id", profile.id),
      supabase.from("savings").select("emergency_fund, total_accumulated, monthly_emergency_contribution").eq("profile_id", profile.id).maybeSingle(),
      supabase.from("savings_goals").select("goal_name, current_amount, target_amount, monthly_contribution, is_active").eq("profile_id", profile.id)
    ]);
    const firstError = [income, debts, fixed, variable, savings, goals].find((r) => r.error)?.error;
    if (firstError) return { content: [{ type: "text", text: firstError.message }], isError: true };
    const sum = (rows, key) => (rows ?? []).reduce((acc, row) => acc + Number(row[key] ?? 0), 0);
    const totalIncome = sum(income.data, "amount");
    const totalDebtPayments = sum(debts.data, "minimum_payment");
    const debtBalance = sum(debts.data, "balance");
    const totalFixed = (fixed.data ?? []).reduce((acc, e) => {
      const amount = Number(e.amount ?? 0);
      if (e.frequency_type === "annual") return acc + (e.payment_month === month ? amount : 0);
      return acc + amount;
    }, 0);
    const totalVariable = sum(variable.data, "amount");
    const goalContributions = (goals.data ?? []).filter((g) => g.is_active).reduce((acc, g) => acc + Number(g.monthly_contribution ?? 0), 0);
    const emergencyContribution = Number(savings.data?.monthly_emergency_contribution ?? 0);
    const savingsBalance = Number(savings.data?.emergency_fund ?? 0) + Number(savings.data?.total_accumulated ?? 0) + sum(goals.data, "current_amount");
    const cashflow = totalIncome - totalDebtPayments - totalFixed - totalVariable - goalContributions - emergencyContribution;
    const summary = {
      profile: { name: profile.name, type: profile.type },
      monthly_income: totalIncome,
      monthly_debt_minimum_payments: totalDebtPayments,
      total_debt_balance: debtBalance,
      monthly_fixed_expenses: totalFixed,
      monthly_variable_expenses: totalVariable,
      monthly_savings_goal_contributions: goalContributions,
      monthly_emergency_fund_contribution: emergencyContribution,
      total_savings_balance: savingsBalance,
      monthly_cashflow: cashflow,
      currency: "GBP"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-debts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_debts_default = defineTool2({
  name: "list_debts",
  title: "List debts",
  description: "List the debts on the signed-in user's active budget profile with balance, APR, minimum payment and payment day.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { supabase, profile } = await activeProfile(ctx);
    const { data, error } = await supabase.from("debts").select("id, name, bank, balance, apr, minimum_payment, payment_day, end_date").eq("profile_id", profile.id).order("balance", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { debts: data ?? [], currency: "GBP" }
    };
  }
});

// src/lib/mcp/tools/list-savings-goals.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_savings_goals_default = defineTool3({
  name: "list_savings_goals",
  title: "List savings goals",
  description: "List the savings goals on the signed-in user's active budget profile with progress, monthly contribution and target date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { supabase, profile } = await activeProfile(ctx);
    const { data, error } = await supabase.from("savings_goals").select("id, goal_name, goal_description, current_amount, target_amount, monthly_contribution, target_date, is_active").eq("profile_id", profile.id).order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const goals = (data ?? []).map((g) => ({
      ...g,
      progress_percent: Number(g.target_amount) > 0 ? Math.round(Number(g.current_amount ?? 0) / Number(g.target_amount) * 100) : 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(goals, null, 2) }],
      structuredContent: { savings_goals: goals, currency: "GBP" }
    };
  }
});

// src/lib/mcp/tools/add-variable-expense.ts
import { defineTool as defineTool4, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var add_variable_expense_default = defineTool4({
  name: "add_variable_expense",
  title: "Add variable expense",
  description: "Record a one-off variable expense on the signed-in user's active budget profile.",
  inputSchema: {
    name: z.string().trim().min(1).describe("What the expense was for, e.g. 'Groceries'."),
    amount: z.number().positive().describe("Expense amount in GBP."),
    date: z.string().optional().describe("Date of the expense as YYYY-MM-DD. Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, amount, date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (date && !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      throw new ToolError("date must be formatted as YYYY-MM-DD");
    }
    const { supabase, profile } = await activeProfile(ctx);
    const { data, error } = await supabase.from("variable_expenses").insert({
      user_id: ctx.getUserId(),
      profile_id: profile.id,
      name,
      amount,
      date: date ?? (/* @__PURE__ */ new Date()).toISOString().split("T")[0]
    }).select("id, name, amount, date").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added expense "${data.name}" of \xA3${Number(data.amount).toFixed(2)} on ${data.date}.` }],
      structuredContent: { expense: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eyejsldngbqnygxbgahe";
var mcp_default = defineMcp({
  name: "budget-planner",
  title: "Budget Planner",
  version: "0.1.0",
  instructions: "Tools for Budget Planner, a UK household budgeting app. Use `get_budget_summary` for the signed-in user's monthly income, expenses, savings and cashflow; `list_debts` and `list_savings_goals` for detail; `add_variable_expense` to log a one-off spend. All amounts are in GBP and scoped to the user's active budget profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_budget_summary_default, list_debts_default, list_savings_goals_default, add_variable_expense_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
